name:                StringMatch
version:             0.1.0.0
github:              "cyoon1729/StringMatch"
license:             BSD3
author:              "Eumin Hong and Chris Yoon"
maintainer:          "cjy2129@columbia.edu"
copyright:           "2021 Chris Yoon"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            StringMatch Haskell implementation
# category:            String

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/cyoon1729/StringMatch>

dependencies:
- base >= 4.7 && < 5
- bytestring
- containers
- directory
- deepseq
- parallel
- unix
- unix-bytestring

default-extensions: 
- PackageImports

library:
  source-dirs: src

executables:
  StringMatch-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -eventlog
    dependencies:
    - StringMatch

tests:
  StringMatch-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - StringMatch
